/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dados.ClienteDAO;
import dados.PedidoDAO;
import java.awt.Color;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import negocio.Cliente;
import negocio.Pedido;

/**
 *
 * @author massilva
 */
public class CadastroPedido extends javax.swing.JFrame {

    private String msg_busca = "Digite o nome do cliente";
    DefaultTableModel modelo;
    Color bgcolor;
    Cliente c;
    /**
     * Creates new form CadastroPedido
     */
    public CadastroPedido(Color bgcolor) {
        initComponents();
        jT_busca.setText(msg_busca);
        try {
            atualizarLista("");
        } catch (Exception ex) {
            Logger.getLogger(CadastroPedido.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDesktopPane1.setBackground(bgcolor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jL_titulo = new javax.swing.JLabel();
        jL_busca = new javax.swing.JLabel();
        jT_busca = new javax.swing.JTextField();
        jL_pedido = new javax.swing.JLabel();
        jL_1 = new javax.swing.JLabel();
        jL_2 = new javax.swing.JLabel();
        jL_3 = new javax.swing.JLabel();
        jL_4 = new javax.swing.JLabel();
        jL_5 = new javax.swing.JLabel();
        jL_6 = new javax.swing.JLabel();
        jL_7 = new javax.swing.JLabel();
        jL_8 = new javax.swing.JLabel();
        jT_pedido_1 = new javax.swing.JTextField();
        jT_pedido_2 = new javax.swing.JTextField();
        jT_pedido_3 = new javax.swing.JTextField();
        jT_pedido_4 = new javax.swing.JTextField();
        jT_pedido_5 = new javax.swing.JTextField();
        jT_pedido_6 = new javax.swing.JTextField();
        jT_pedido_7 = new javax.swing.JTextField();
        jT_pedido_8 = new javax.swing.JTextField();
        jB_salvar = new javax.swing.JButton();
        jB_voltar = new javax.swing.JButton();
        jS_lista = new javax.swing.JScrollPane();
        jT_lista = new javax.swing.JTable();
        jT_endereco = new javax.swing.JTextField();
        jL_endereco = new javax.swing.JLabel();
        jL_endereco1 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Pedido");
        setAlwaysOnTop(true);
        setResizable(false);

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 204));

        jL_titulo.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        jL_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_titulo.setText("Cadastro de Pedido");
        jL_titulo.setBounds(0, 0, 800, 80);
        jDesktopPane1.add(jL_titulo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jL_busca.setText("Busca pelo cliente");
        jL_busca.setBounds(260, 90, 160, 30);
        jDesktopPane1.add(jL_busca, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jT_busca.setForeground(new java.awt.Color(187, 187, 187));
        jT_busca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jT_buscaFocusLost(evt);
            }
            public void focusGained(java.awt.event.FocusEvent evt) {
                jT_buscaFocusGained(evt);
            }
        });
        jT_busca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jT_buscaKeyReleased(evt);
            }
        });
        jT_busca.setBounds(420, 90, 360, 28);
        jDesktopPane1.add(jT_busca, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jL_pedido.setText("Pedido");
        jL_pedido.setBounds(20, 230, 400, 30);
        jDesktopPane1.add(jL_pedido, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jL_1.setText("#1");
        jL_1.setBounds(30, 260, 20, 30);
        jDesktopPane1.add(jL_1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jL_2.setText("#2");
        jL_2.setBounds(30, 300, 20, 30);
        jDesktopPane1.add(jL_2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jL_3.setText("#3");
        jL_3.setBounds(30, 340, 20, 30);
        jDesktopPane1.add(jL_3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jL_4.setText("#4");
        jL_4.setBounds(30, 380, 20, 30);
        jDesktopPane1.add(jL_4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jL_5.setText("#5");
        jL_5.setBounds(410, 260, 20, 30);
        jDesktopPane1.add(jL_5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jL_6.setText("#6");
        jL_6.setBounds(410, 300, 20, 30);
        jDesktopPane1.add(jL_6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jL_7.setText("#7");
        jL_7.setBounds(410, 340, 20, 30);
        jDesktopPane1.add(jL_7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jL_8.setText("#8");
        jL_8.setBounds(410, 380, 20, 30);
        jDesktopPane1.add(jL_8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jT_pedido_1.setBounds(50, 260, 350, 28);
        jDesktopPane1.add(jT_pedido_1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jT_pedido_2.setBounds(50, 300, 350, 28);
        jDesktopPane1.add(jT_pedido_2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jT_pedido_3.setBounds(50, 340, 350, 28);
        jDesktopPane1.add(jT_pedido_3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jT_pedido_4.setBounds(50, 380, 350, 28);
        jDesktopPane1.add(jT_pedido_4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jT_pedido_5.setBounds(430, 260, 350, 28);
        jDesktopPane1.add(jT_pedido_5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jT_pedido_6.setBounds(430, 300, 350, 28);
        jDesktopPane1.add(jT_pedido_6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jT_pedido_7.setBounds(430, 340, 350, 28);
        jDesktopPane1.add(jT_pedido_7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jT_pedido_8.setBounds(430, 380, 350, 28);
        jDesktopPane1.add(jT_pedido_8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jB_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/imagem/save.png"))); // NOI18N
        jB_salvar.setText("Salvar");
        jB_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_salvarActionPerformed(evt);
            }
        });
        jB_salvar.setBounds(20, 530, 160, 80);
        jDesktopPane1.add(jB_salvar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jB_voltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/imagem/back.png"))); // NOI18N
        jB_voltar.setMnemonic('v');
        jB_voltar.setText("Voltar");
        jB_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_voltarActionPerformed(evt);
            }
        });
        jB_voltar.setBounds(620, 530, 160, 80);
        jDesktopPane1.add(jB_voltar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jT_lista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jT_lista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jT_listaMouseClicked(evt);
            }
        });
        jT_lista.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jT_listaFocusLost(evt);
            }
            public void focusGained(java.awt.event.FocusEvent evt) {
                jT_listaFocusGained(evt);
            }
        });
        jS_lista.setViewportView(jT_lista);

        jS_lista.setBounds(20, 120, 760, 110);
        jDesktopPane1.add(jS_lista, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jT_endereco.setBounds(20, 440, 760, 28);
        jDesktopPane1.add(jT_endereco, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jL_endereco.setText("Endereço de entrega");
        jL_endereco.setBounds(20, 420, 180, 20);
        jDesktopPane1.add(jL_endereco, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jL_endereco1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jL_endereco1.setText("Valor:");
        jL_endereco1.setBounds(400, 480, 60, 40);
        jDesktopPane1.add(jL_endereco1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#,##0.00"))));
        jFormattedTextField1.setBounds(460, 480, 130, 40);
        jDesktopPane1.add(jFormattedTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private void atualizarLista(String nome) throws Exception{
        
        this.setAlwaysOnTop(false);
        
        String [] colunas = new String []{"Id","Nome","Telefone","Endereco"};
        modelo = new DefaultTableModel(null, colunas){
            
        @Override
        public boolean isCellEditable(int row, int col){
                return false;
            }
        };
        
         ClienteDAO f = new ClienteDAO();
         List listar = f.listaCliente(nome);
        if(listar.isEmpty()){
            jB_salvar.setVisible(false);                 
        }
        
        Iterator it = listar.iterator();
        while(it.hasNext()){
            Cliente l = (Cliente)it.next();
            modelo.addRow(new Object[]{l.getId(),l.getNome(),l.getTelefone(),l.getEndereco()});
        }
        
        jT_lista.setModel(modelo);
        jT_lista.setShowHorizontalLines(false);
        jT_lista.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jT_lista.getColumnModel().getColumn(0).setPreferredWidth(80);   
        jT_lista.getColumnModel().getColumn(1).setPreferredWidth(120);  
    }
    
    private void jT_buscaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_buscaFocusGained
        if(jT_busca.getText().equals(msg_busca)){
            jT_busca.setText("");
            jT_busca.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_jT_buscaFocusGained

    private void jT_buscaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jT_buscaKeyReleased
        if(!jT_busca.getText().isEmpty()){
            jT_busca.setForeground(Color.BLACK);            
        }
        
        String filtro = jT_busca.getText();
        
        try {        
            atualizarLista(filtro);
        } catch (Exception ex) {
            Logger.getLogger(CadastroPedido.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jT_buscaKeyReleased

    private void jT_buscaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_buscaFocusLost
        if(jT_busca.getText().isEmpty())
        {
            jT_busca.setForeground(Color.gray);
            jT_busca.setText(msg_busca);
        }
    }//GEN-LAST:event_jT_buscaFocusLost

    private void jB_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_voltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jB_voltarActionPerformed

    private void jT_listaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_listaFocusGained
        // TODO add your handling code here:
        int numLinhaSelecionada = jT_lista.getSelectedRow();         
        int id = Integer.parseInt(jT_lista.getValueAt(numLinhaSelecionada, 0).toString());
        
        ClienteDAO cD = new ClienteDAO();
        c = cD.buscaClienteId(id);
                
        jT_endereco.setText(c.getEndereco());
        
    }//GEN-LAST:event_jT_listaFocusGained

    private void jT_listaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jT_listaFocusLost
        // TODO add your handling code here:
        
        int numLinhaSelecionada = jT_lista.getSelectedRow();         
        int id = Integer.parseInt(jT_lista.getValueAt(numLinhaSelecionada, 0).toString());
        
        ClienteDAO cD = new ClienteDAO();
        c = cD.buscaClienteId(id);
                
        jT_endereco.setText(c.getEndereco());
        
    }//GEN-LAST:event_jT_listaFocusLost

    private void jT_listaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jT_listaMouseClicked
        // TODO add your handling code here:
        int numLinhaSelecionada = jT_lista.getSelectedRow();         
        int id = Integer.parseInt(jT_lista.getValueAt(numLinhaSelecionada, 0).toString());
        
        ClienteDAO cD = new ClienteDAO();
        c = cD.buscaClienteId(id);
                
        jT_endereco.setText(c.getEndereco());
        
    }//GEN-LAST:event_jT_listaMouseClicked

    private void jB_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_salvarActionPerformed
        // TODO add your handling code here:
        String  pedido1, pedido2, pedido3, pedido4, pedido5, pedido6, pedido7, pedido8;
        String  endereco, complemento;
        PedidoDAO pD = new PedidoDAO();
        
        endereco = jT_endereco.getText();
       
        
        pedido1 = jT_pedido_1.getText();
        pedido2 = jT_pedido_2.getText();
        pedido3 = jT_pedido_3.getText();
        pedido4 = jT_pedido_4.getText();
        pedido5 = jT_pedido_5.getText();
        pedido6 = jT_pedido_6.getText();
        pedido7 = jT_pedido_7.getText();
        pedido8 = jT_pedido_8.getText();
        
        Pedido p = new Pedido(c);
        p.setPedido1(pedido1);
        p.setPedido2(pedido2);
        p.setPedido3(pedido3);
        p.setPedido4(pedido4);
        p.setPedido5(pedido5);
        p.setPedido6(pedido6);
        p.setPedido7(pedido7);
        p.setPedido8(pedido8);
        
        p.setEndereco(endereco);
        
        try {
            if(pD.cadastraPedido(p)){
                JOptionPane.showMessageDialog(this, "Pedido cadastrado com sucesso.");
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(this, "Erro ao cadastrar!");
            }       
        } catch (Exception ex) {
            Logger.getLogger(CadastroPedido.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jB_salvarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_salvar;
    private javax.swing.JButton jB_voltar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jL_1;
    private javax.swing.JLabel jL_2;
    private javax.swing.JLabel jL_3;
    private javax.swing.JLabel jL_4;
    private javax.swing.JLabel jL_5;
    private javax.swing.JLabel jL_6;
    private javax.swing.JLabel jL_7;
    private javax.swing.JLabel jL_8;
    private javax.swing.JLabel jL_busca;
    private javax.swing.JLabel jL_endereco;
    private javax.swing.JLabel jL_endereco1;
    private javax.swing.JLabel jL_pedido;
    private javax.swing.JLabel jL_titulo;
    private javax.swing.JScrollPane jS_lista;
    private javax.swing.JTextField jT_busca;
    private javax.swing.JTextField jT_endereco;
    private javax.swing.JTable jT_lista;
    private javax.swing.JTextField jT_pedido_1;
    private javax.swing.JTextField jT_pedido_2;
    private javax.swing.JTextField jT_pedido_3;
    private javax.swing.JTextField jT_pedido_4;
    private javax.swing.JTextField jT_pedido_5;
    private javax.swing.JTextField jT_pedido_6;
    private javax.swing.JTextField jT_pedido_7;
    private javax.swing.JTextField jT_pedido_8;
    // End of variables declaration//GEN-END:variables
}
