/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dados.ClienteDAO;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import negocio.Cliente;

/**
 *
 * @author massilva
 */
public class CadastroCliente extends javax.swing.JFrame {

    /**
     * Creates new form CadastroCliente
     */
    int id;
    public CadastroCliente(Color bgcolor){
        initComponents();
        jDesktopPane1.setBackground(bgcolor);     
    }
    
     public CadastroCliente(Color bgcolor,int id){
        initComponents();
        Cliente c;
        ClienteDAO cD = new ClienteDAO();
        
        c = cD.buscaClienteId(id);
        this.id = id;
        jT_nome.setText(c.getNome());
        jT_telefone.setText(c.getTelefone());
        jT_endereco.setText(c.getEndereco());
        
        
        jB_salvar.setText("Atualizar");
        jDesktopPane1.setBackground(bgcolor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jT_endereco = new javax.swing.JTextField();
        jT_telefone = new javax.swing.JTextField();
        jT_nome = new javax.swing.JTextField();
        jL_telefone = new javax.swing.JLabel();
        jL_nome = new javax.swing.JLabel();
        jL_endereco = new javax.swing.JLabel();
        jB_salvar = new javax.swing.JButton();
        jB_cancelar = new javax.swing.JButton();
        jL_titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Cliente");
        setAlwaysOnTop(true);
        setResizable(false);

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 204));
        jT_endereco.setBounds(150, 200, 420, 30);
        jDesktopPane1.add(jT_endereco, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jT_telefone.setBounds(150, 150, 200, 30);
        jDesktopPane1.add(jT_telefone, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jT_nome.setBounds(150, 100, 420, 30);
        jDesktopPane1.add(jT_nome, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jL_telefone.setText("Telefone");
        jL_telefone.setBounds(30, 150, 120, 30);
        jDesktopPane1.add(jL_telefone, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jL_nome.setText("Nome");
        jL_nome.setBounds(30, 100, 120, 30);
        jDesktopPane1.add(jL_nome, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jL_endereco.setText("Endereço");
        jL_endereco.setBounds(30, 200, 120, 30);
        jDesktopPane1.add(jL_endereco, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jB_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/imagem/save.png"))); // NOI18N
        jB_salvar.setMnemonic('s');
        jB_salvar.setText("Salvar");
        jB_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_salvarActionPerformed(evt);
            }
        });
        jB_salvar.setBounds(20, 300, 120, 80);
        jDesktopPane1.add(jB_salvar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jB_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/imagem/remove.png"))); // NOI18N
        jB_cancelar.setMnemonic('c');
        jB_cancelar.setText("Cancelar");
        jB_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_cancelarActionPerformed(evt);
            }
        });
        jB_cancelar.setBounds(450, 300, 120, 80);
        jDesktopPane1.add(jB_cancelar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jL_titulo.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        jL_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_titulo.setText("Cadastro de Cliente");
        jL_titulo.setBounds(0, 0, 600, 80);
        jDesktopPane1.add(jL_titulo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jB_cancelarActionPerformed

    private void jB_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_salvarActionPerformed
        // TODO add your handling code here:
        String nome = jT_nome.getText();
        String endereco = jT_endereco.getText();
        
        String telefone = jT_telefone.getText();
        ClienteDAO cD = new ClienteDAO();
        
        Cliente c = new Cliente(nome, endereco, telefone);
        c.setId(id);
        
        if (jB_salvar.getText().equals("Atualizar")){
            try {
                if(cD.editarCliente(c)){ 
                    JOptionPane.showMessageDialog(this, "Alteração de cadastro efetuada com sucesso!", "Confirmação do Sistema", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                }
            } catch (Exception ex) {
                Logger.getLogger(CadastroCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
        
            if(cD.cadastraCliente(c)){
                JOptionPane.showMessageDialog(this, "Cliente cadastrado com sucesso!");
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(this, "Erro ao cadastrar!");
            }        
        }
        
        
    }//GEN-LAST:event_jB_salvarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_cancelar;
    private javax.swing.JButton jB_salvar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jL_endereco;
    private javax.swing.JLabel jL_nome;
    private javax.swing.JLabel jL_telefone;
    private javax.swing.JLabel jL_titulo;
    private javax.swing.JTextField jT_endereco;
    private javax.swing.JTextField jT_nome;
    private javax.swing.JTextField jT_telefone;
    // End of variables declaration//GEN-END:variables
}
